version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/seat-sleuth-server'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'npm'
    directory: '/seat-sleuth-client'
    schedule:
      interval: 'weekly'
