name: seat-sleuth
services:
  database:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: seat-sleuth-user
      POSTGRES_PASSWORD: seat-sleuth-password-12345
      POSTGRES_DB: seat-sleuth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U seat-sleuth-user -h database -d seat-sleuth']
      interval: 1s
      retries: 10
  client:
    container_name: client
    image: jaycebordelon/seat-sleuth-client:prod
    build:
      context: ./seat-sleuth-client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./seat-sleuth-client:/app
      - node_modules_client:/app/node_modules
      - ./seat-sleuth-server/src/types/shared:/app/src/shared
    env_file:
      - ./seat-sleuth-client/.env
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_API_BASE_URL=http://localhost:4000/api/
    command: sh -c "npm run dev"
    depends_on:
      server:
        condition: service_healthy
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5173']
      interval: 1s
      retries: 10
  server:
    container_name: server
    image: jaycebordelon/seat-sleuth-server:prod
    build:
      context: ./seat-sleuth-server
      dockerfile: Dockerfile
    env_file:
      - ./seat-sleuth-server/.env
    environment:
      - DATABASE_URL=postgresql://seat-sleuth-user:seat-sleuth-password-12345@database:5432/seat-sleuth
    ports:
      - '4000:4000'
    volumes:
      - ./seat-sleuth-server:/app
      - node_modules_server:/app/node_modules
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/api/health']
      interval: 1s
      retries: 10
volumes:
  postgres_data:
    name: seat-sleuth-postgres-data
  node_modules_client:
    name: seat-sleuth-client-modules
  node_modules_server:
    name: seat-sleuth-server-modules
