name: seat-sleuth

services:
  database:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: seat-sleuth-user
      POSTGRES_PASSWORD: seat-sleuth-password-12345
      POSTGRES_DB: seat-sleuth
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U seat-sleuth-user -h database -d seat-sleuth']
      interval: 1s
      retries: 10

  client:
    container_name: client
    build:
      context: ./seat-sleuth-client
      dockerfile: Dockerfile
    image: seat-sleuth-client:latest
    ports:
      - '8080:80'
    environment:
      - VITE_HOST=0.0.0.0
      - VITE_API_BASE_URL=http://localhost:4000/api/

  server:
    container_name: server
    build:
      context: ./seat-sleuth-server
      dockerfile: Dockerfile
    image: seat-sleuth-server:latest
    ports:
      - '4000:4000'
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://seat-sleuth-user:seat-sleuth-password-12345@database:5432/seat-sleuth
      - CLIENT_URL=http://localhost:8080
      - NODE_ENV=production
    env_file:
      - ./seat-sleuth-server/.env
    command: sh -c "npx prisma migrate reset --force && npx prisma generate && node dist/server.js"
