services:
  backend_3001:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
  
  backend_5001:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend_5001
      - backend_3001 
  
  