version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: group9-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: flask run --host=0.0.0.0 --port=8000 --debug