version: '3'

services:
  backend:
    build:
      context: ./fastapi-backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb+srv://admin:admin123@cluster0.tfjwq.mongodb.net/events?retryWrites=true&w=majority&appName=Cluster0
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
