---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: seatsleuth-db
  labels:
    app: seatsleuth-db
spec:
  selector:
    matchLabels:
      app: seatsleuth-db
  replicas: 1
  template:
    metadata:
      labels:
        app: seatsleuth-db
    spec:
      containers:
        - image: docker.io/library/postgres:latest
          name: seatsleuth-db
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          livenessProbe:
            tcpSocket:
              port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: seatsleuth-db
spec:
  selector:
    app: seatsleuth-db
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatsleuth
  labels:
    app: seatsleuth
spec:
  selector:
    matchLabels:
      app: seatsleuth
  replicas: 1
  template:
    metadata:
      labels:
        app: seatsleuth
    spec:
      containers:
        - image: seatsleuth:release
          imagePullPolicy: Never
          name: seatsleuth
          command: ['./script/run']
          ports:
            - containerPort: 3000
          env:
            - name: APP_DATABASE__HOST
              value: seatsleuth-db
            - name: APP_DATABASE__PORT
              value: '5432'
---
apiVersion: v1
kind: Service
metadata:
  name: seatsleuth
spec:
  type: LoadBalancer
  selector:
    app: seatsleuth
  ports:
    - port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: seatsleuth-redis
spec:
  selector:
    app: seatsleuth-redis
  ports:
    - port: 6379
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seatsleuth
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - seatsleuth.smallercircles.dev
      secretName: seatsleuth-tls
  rules:
    - host: seatsleuth.smallercircles.dev
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: seatsleuth
                port:
                  number: 3000
