name: ESLint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "32 20 * * 2"

jobs:
  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for ESLint config
        run: |
          if [ ! -f .eslintrc.js ]; then 
            echo "❌ ESLint config file missing. Skipping linting."; 
            exit 1; 
          fi

      - name: Install Dependencies
        run: |
          if [ -f package.json ]; then npm ci; else echo "❌ No package.json found. Skipping ESLint."; exit 1; fi

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: |
          npx eslint . --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif || echo '{}' > eslint-results.sarif

      - name: Upload analysis results to GitHub
        if: success() && hashFiles('eslint-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
