name: Server Continuous Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./seat-sleuth-server/package-lock.json

    - name: Debug - List root directory files
      run: ls -la

    - name: Debug - List files in seat-sleuth-server
      run: ls -la
      working-directory: ./seat-sleuth-server

    - name: Install dependencies
      run: npm ci
      working-directory: ./seat-sleuth-server

    - name: Build
      run: npm run build --if-present
      working-directory: ./seat-sleuth-server

    - name: Run tests
      run: npm test
      working-directory: ./seat-sleuth-server
